### PR TITLE
probability reporting

### LINKED ISSUE #153: Report joint probability of solution, and next best solution
* report Pr1*Pr2*...*Pr_n for the selected solution
 * also report same number for 2nd best, or M best solutions

We can also give an ad-hoc confidence score which is the probability of the selected solution divided by the next best (infinite if there is only one solution). Intuitively, if the two best solutions are close we have lower confidence, if it's 100x more likely we can have high confidence.

Note that we can also obtain a more accurate estimation of the probability by dividing the probability of a solution by the sum of all probabilities of all solutions. This will be higher than the simple joint probability when there are cases where solutions have a posterior probability of zero ie unsats. 

As a trivial example, given an ontology

    A Equiv B

and prior probabilities

    Pr(A Equiv B) = 0.1

naive calculation gives Pr=0.1 for the full ontology. However, there are no other possibilities so we are forced to update our prior belief

### PR DESCRIPTION
**Pull request by cmungall**
Fixes #153

### CODE REVIEW

**Review by balhoff — COMMENTED** [review]
Looks good, but do we want to convert out of log probability everywhere that we print to the console? There are two other places. I can add if that's what you were wanting.

**Comment by balhoff** [comment]
I think the log probabilities are easier to read. I updated the logging and get this:

```
2021.02.05 17:35:51:799 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluate:33 - Max possible joint probability: 1.0400844760025345E-109
2021.02.05 17:35:54:754 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 5.978263055847241E-224
2021.02.05 17:35:55:163 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 2.9142749561642797E-221
2021.02.05 17:35:55:318 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 1.9580804262254683E-217
2021.02.05 17:35:55:368 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 1.9580804262254683E-217
2021.02.05 17:35:55:384 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 2.7101459186510343E-220
2021.02.05 17:35:55:434 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 1.1357036811433335E-224
2021.02.05 17:35:55:531 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 7.43437488817471E-222
2021.02.05 17:35:55:550 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 2.4837057001408788E-217
2021.02.05 17:35:55:610 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 2.3036370368807653E-218
2021.02.05 17:35:55:616 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 9.136330506341654E-225
2021.02.05 17:35:55:617 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 1.355080609929781E-219
2021.02.05 17:35:55:625 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 5.759092592201509E-218
2021.02.05 17:35:55:617 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 1.230818864439248E-224
2021.02.05 17:35:55:636 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: 2.275261870815781E-216
```

These are easier to compare to one another:

```
2021.02.05 17:38:19:126 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluate:33 - Max possible joint probability: -250.9424731995709
2021.02.05 17:38:21:055 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -487.3196749478947
2021.02.05 17:38:21:062 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -500.8072379961823
2021.02.05 17:38:21:064 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -514.7153093033827
2021.02.05 17:38:21:073 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -497.61734406230494
2021.02.05 17:38:21:078 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -488.11707214982846
2021.02.05 17:38:21:162 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -515.6518083884569
2021.02.05 17:38:21:166 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -505.0873646772924
2021.02.05 17:38:21:185 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -499.33103199611287
2021.02.05 17:38:21:196 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -510.24142668785305
2021.02.05 17:38:21:209 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -517.568731000639
2021.02.05 17:38:21:219 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -519.1345378676332
2021.02.05 17:38:21:224 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -504.55674207211274
2021.02.05 17:38:21:226 [zio-def...] [INFO ] org.monarchinitiative.boomer.Boom.evaluateInOrder:50 - Found joint probability: -511.32805066190696
```

**Comment by cmungall** [comment]
Maybe both? When working with smaller cliques the probabilities are not
ridiculously small,  and are more intuitive

**Comment by cmungall** [comment]
Maybe both? There are cases withs small cliques where the probability is more "meaningful". But no strong opinions - the other part of the PR was just reporting some kind of probality in the hotspots file

**Comment by balhoff** [comment]
This got out of date, and I think it's now superseded by #271 (although I am still using log probabilities there).

**Pull request closed without merging**
